//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ESurvey.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class AnsweredQuestionsOptions
    {
        public int Id { get; set; }
        public int AnswerId { get; set; }
        public int QuestionId { get; set; }
        public Nullable<bool> Answer { get; set; }
        public string Extended_Answer { get; set; }
    
        public virtual AnsweredQuestions AnsweredQuestions { get; set; }
        public virtual QuestionAnswers QuestionAnswers { get; set; }
    }
}
