//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ESurvey.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class AnsweredQuestions
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AnsweredQuestions()
        {
            this.AnsweredQuestionsOptions = new HashSet<AnsweredQuestionsOptions>();
        }
    
        public int Id { get; set; }
        public int SessionId { get; set; }
        public int QuestionId { get; set; }
    
        public virtual Questions Questions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AnsweredQuestionsOptions> AnsweredQuestionsOptions { get; set; }
        public virtual SurveySessions SurveySessions { get; set; }
    }
}
