//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ESurvey.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class SurveySessions
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SurveySessions()
        {
            this.AnsweredQuestions = new HashSet<AnsweredQuestions>();
        }
    
        public int Id { get; set; }
        public int SurveyId { get; set; }
        public int VoterId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AnsweredQuestions> AnsweredQuestions { get; set; }
        public virtual Survey Survey { get; set; }
        public virtual Voters Voters { get; set; }
    }
}
